### ISSUE TITLE
Silent Failure after Update or Apply of layout URL

### ISSUE THREAD

**Issue by stavrosthewonderchicken** [Invvard/EZLayoutDisplay#35]
(Love this idea -- my Ergo should arrive in the next week or so, and I wasn't keen on printing stuff out! Thanks for making the app!)

## Expected Behavior
Paste in URL to Layout in Settings dialog
Hit Update (or Apply - not actually sure why there are two buttons)
Hit Close
Profit!

## Actual Behavior
Paste in URL to Layout in Settings dialog
Hit Update or Apply
Application crashes out

## Steps to Reproduce the Problem

  1. Paste in URL to Layout in Settings dialog
  2. Hit Update or Apply
  3. :-(

## Specifications

  - EZLayout Version: v0.2.0.2001 (Beta 1)
  - Operating System (incl. Version) : Windows 10 v1803

**Comment by Invvard** [comment]
Hi Stavros,

I'm glad you like the app (or the idea of this app right now) and that you are joining the ErgoDox EZ community :)

Could you give me the URL to your layout, please ? I'll try to reproduce your issue with it.

Thank you for taking time to report your issue !

**Comment by stavrosthewonderchicken** [comment]
Sure, here it is: https://configure.ergodox-ez.com/layouts/XdaB/latest/0

**Comment by Invvard** [comment]
I tried your layout and everything went as expected.
Could you see if there's something in the Window event viewer, please ? (I still have to add a logging system in the app)

**Comment by stavrosthewonderchicken** [comment]
Sure, but I’m on a business trip next couple of days, so it might take a while.

**Comment by Invvard** [comment]
No worries, I just want to solve your issue so you can use the app along with your brand new ErgoDox EZ :)

**Comment by stavrosthewonderchicken** [comment]
OK, here are the two Event Viewer, er, events when it crashes out:
---------------------------------
Faulting application name: InvvardDev.EZLayoutDisplay.Desktop.exe, version: 0.2.0.2001, time stamp: 0x5c6dd482
Faulting module name: KERNELBASE.dll, version: 10.0.17134.556, time stamp: 0xadca2670
Exception code: 0xe0434352
Fault offset: 0x001118a2
Faulting process id: 0x2fc
Faulting application start time: 0x01d4d0d7e1679a61
Faulting application path: C:\Program Files\ErgodoxEZLayout\InvvardDev.EZLayoutDisplay.Desktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 0b23fc5b-8c97-42df-b390-ae94380d583b
Faulting package full name: 
Faulting package-relative application ID: 
----------------------------------------------------
Application: InvvardDev.EZLayoutDisplay.Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Newtonsoft.Json.JsonReaderException
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(System.Object, Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonObjectContract, Newtonsoft.Json.Serialization.JsonProperty, System.String)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, System.Object)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, System.Object)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(System.Collections.IList, Newtonsoft.Json.JsonReader, Newtonsoft.Json.Serialization.JsonArrayContract, Newtonsoft.Json.Serialization.JsonProperty, System.String)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, System.Object, System.String)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(Newtonsoft.Json.JsonReader, System.Type, Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json.Serialization.JsonProperty, System.Object)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(Newtonsoft.Json.JsonReader, System.Type, Boolean)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(Newtonsoft.Json.JsonReader, System.Type)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(System.String, System.Type, Newtonsoft.Json.JsonSerializerSettings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String, Newtonsoft.Json.JsonSerializerSettings)
   at InvvardDev.EZLayoutDisplay.Desktop.Model.Dictionary.KeyDefinitionDictionary.InitializeKeyDefinitions()
   at InvvardDev.EZLayoutDisplay.Desktop.Helper.EZLayoutMaker..ctor()
   at InvvardDev.EZLayoutDisplay.Desktop.Service.Implementation.LayoutService.PrepareEZLayout(InvvardDev.EZLayoutDisplay.Desktop.Model.ErgodoxLayout)
   at InvvardDev.EZLayoutDisplay.Desktop.ViewModel.SettingsViewModel+<UpdateLayout>d__75.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at InvvardDev.EZLayoutDisplay.Desktop.ViewModel.SettingsViewModel+<SaveSettings>d__70.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at InvvardDev.EZLayoutDisplay.Desktop.App.Main()

**Comment by Invvard** [comment]
OK, I have a strong feeling that you don't have the needed .NET Framework version installed.
Can you [install it](https://www.microsoft.com/en-us/download/details.aspx?id=56116) and see if it's doing the same, please ?

**Comment by stavrosthewonderchicken** [comment]
Seems to be installed already!

".NET Framework 4.7.1 or a later update is already installed on this computer."

**Comment by Invvard** [comment]
OK, so I've been looking around about the KernelBase exception and here are few things I need from you :
1. What is the regional language being used on your system ?
2. Where are located the app files ?
3. Have you tried other layouts beside yours ? If yes, did the app showed the same behavior ?
4. Could you follow [this article from Microsoft](https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system) ?
5. In the Event Viewer are there other instances of the KernelBase error that are NOT related to EZLD ?
The last two points are here because most people reporting this issue are facing corrupted system files and I'd like to put this possibility out before going further.

Thank you for your help !

**Comment by stavrosthewonderchicken** [comment]
1. Country/Region is Korea, display language is US English.
2. In C:\Program Files
3. Tried a few different layouts at random (via search on the Ergo site), same issue.
4. DISM.exe completed without issue. sfc completed with 'Windows Resource Protection did not find any integrity violations.'
5. Nope, can't find any other KernelBase.dll errors. Not many application errors at all.

Sorry to give you grief. As a (hobby) developer myself, I sympathize with trying to debug errors I can't replicate...

**Comment by Invvard** [comment]
2 things you could try :
- Try to execute the soft out from C:/Program Files (from your Documents for example),
- Execute EZLD as an administrator.
Still the same ?

**Comment by Invvard** [comment]
Hey ! Just checking if there was some change to your situation ?

I'll be releasing a new version early next week and right after that I'll start working on adding a logs everywhere. Fortunately, that will help and speed up fixing with next issues.

**Comment by stavrosthewonderchicken** [comment]
Sorry -- been busy getting ready for an overseas trip, and completely forgot (because my Ergo hasn't arrived yet). I'll try your suggestions later today!

**Comment by stavrosthewonderchicken** [comment]
I tried moving the folder elsewhere (to a storage drive), and no luck either running normally or running as administrator.

If it helps at all, there's a pause after hitting Apply before it crashes out, so I think it's failing after/during the point at which it's retrieving the layout from the Ergodox site.

**Comment by Invvard** [comment]
OK, thank you for trying it out!
I'll be out of town and off grid for the next 3 days so I'll get back to you on Monday :)

Again sorry for the delay!

**Comment by stavrosthewonderchicken** [comment]
Good news! Just got back from my trip and the new version seems to be working flawlessly! Thanks!

**Comment by Invvard** [comment]
That's a super nice news !
Well, that means I won't get to the bottom of this but at least it motivated me to add a thorough logging feature !
Enjoy the app !!
